name: Go (Lint)
on: [push, pull_request]
jobs:

  golangci-lint:
    name: runner / golangci-lint (pre-build docker image)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        # uses: reviewdog/action-golangci-lint@v1 # Build with Dockerfile
        uses: docker://reviewdog/action-golangci-lint:v1 # Pre-built image
        with:
          github_token: ${{ secrets.github_token }}
